<<<<<<< HEAD
os: linux
dist: bionic

language: minimal

jobs:
  include:

    - name: CD
      language: ruby
      rvm: 2.7.0

      addons:
        apt:
          packages:
            # required to avoid SSL error (for htmlproofer)
            - libcurl4-openssl-dev

      cache:
        directories:
          - $TRAVIS_BUILD_DIR/vendor/bundle

      before_install:
        # match the Gemfile.lock, travis' bundler is 2.1.2
        - gem install bundler:2.2.4
        - bundle config path 'vendor/bundle'

      install:
        # overriding to drop the travis `--development` flag
        - bundle install --jobs=3 --retry=3

      script:
        - eval "$BUILD_CMD"

      git:
        depth: false # for posts' lastmod

    - name: Flush Starter
      script:
        - eval "$FLUSH_STARTER"

before_script:
  - git -C "$HOME" clone "$BUILDER_REPO" --depth=1 -q

branches:
  only: /.*-stable$/

notifications:
  email:
    recipients:
      - secure: "fFLqX7uOzFA8RE2AUFlU1mmxMw+rdV6DnODJ/1Gl+3ecNtrv5LeH3c5a4a5ShQqYTrx9BPfD40VRN7UB+lzOdXiWLI9yDGRPPxGG26/WfrKpdQPZilc8zAOEeDnLAJeGZLsUvgmNb3KCXW6S8NPqqh34CfWcTIzjCARhRgO33wcs8X5wP5cugtNqO5Ew/pUcfWcmiuXNX0GNT6l+nL5A7yN+IO5mRHqSRmlfYd5EHhGMTIL4La+Cd1CNv1m4Dl0Ah2cDeJwi5wLnVbqAgunLhAYmDtxIOCVYMTBrP37UiNe/7QeFelyJfODsmMg1mx3WCykbXydC753WVoAlTg6nNoeeI9fmK+/tuLK+sx/KnYfTVGBXQYq39DyV/2o/IfCzEAKImlzFKGD8R13+ddu4B5UML+cby5KBvhTKIGaC5tKoe39z/31UPpy11/EHMCof2BUOzIgu5Hsv4OSNJlw3oRE31oOPn8xP4e7uWR8bRUhAgzN0Cn0ht+UfpemfGAXrp0M3IXQdc9L4azEFqxRhivMTLK/P6INay7IM+DJ30Ht2dWylGw/sxcRTqyNm3YomJQnXIO4xeqTSLulWr80FFHTys3JEDJYrcKvJmpwLFEAOZtwKsZ6ZShrOIA4LE5fgQtakH3ZLJG9a7jVSlMcNIfaSKgjdDQOe6CoRQL7KouA="
    on_success: never

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
=======
language: ruby
cache: bundler
rvm:
  - 2.5.0
deploy:
  provider: rubygems
  api_key:
    secure: g+XZSOuL/X368f8j3xQCwE5yCJQMse8AcY1rLsYxxjj/ymS2sw59w3LCnfz13EJ0wbaeXCLQiU+RzaRLzBxHDKpoid6ghsO+th5ew9tW+ceCryCWsEvXfwtUCI9PfLQpUull0xBUA4C0eh2k9p9jIMDSEWN0syh6hPaYEOeM5Iev9QU0q2bTdzXiQS8sl8Wc46DiRAt3JbCkq6Q//kIvDmx8+0ZKjHjxrbZLbiG+v5EbNpcGjehtbgMVp0V1ZHiWLjX+PBuTg4sGsnDFUB6sq/JdHGj5baJ0ACaoIad3FQjV0a3jtasTIAmY8zyDG4q9TBu+MLbTrbKC6yv2Ld+PN3rOA7HwEME2iMSJTDhB7Q3urakoXoiX48umNmhIMloPJ/AydqFKzK16rwkNG+vZR7iTbE+3vd0ToYY/FL4w4WNilAhnYde8/abogQJNsug5GWTUf8ZkCyEXT4F9zfmrY99keVufaQs8Um0VwTBJoZRPNhmMzagA3nn+RR6PeiO5NE7QBSiWVxYE3trApzRK6023dxZT1ZmedSkuKto8Gajmv8XUvdFQWrtibkr4tYrJhoO/qOZpQ+jYGmtx3DEZw675TzaZN4Mns5W5ZCxvbMbY2/Rap0Sd4jqfkC6HfLPkteyk3K7Xy2o56KbzhZG15b3It5CDxwKPaFcHEI7xfdQ=
  gem: lone-wolf-theme
  on:
    repo: manid2/lone-wolf-theme
    tags: true
branches:
  # blocklist
  except:
    - /^(?i:tmp)/.*$/
    - /^(?i:wip)/.*$/
>>>>>>> 7675f191ddcf2917855a738ddfcea95a20678310
